server:
  port: 9999
spring:
  application:
    name: files   # jwt
  datasource:     #数据库相关配置
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://124.223.77.57:3306/test?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456

jwt:
  token:
    secret-key: secret-key
    expire-length: 3600000 # 1h


